---
- hosts: bgp_router
  gather_facts: false
  connection: local

  tasks:
  - name: gathering router configuration 
    ios_facts:
      provider: "{{ connector }}"
      gather_subset: "!config"

  - name: show router configuration 
    debug: msg={{ ansible_net_interfaces }}
