---
- hosts: bgp_router
  gather_facts: false
  connection: local

  tasks:
  - name: gathering ip router
    register: result
    ios_command:
      provider: "{{ connector }}"
      commands: "show ip route"

  - name: show ip route
    debug: msg="{{ result.stdout_lines }}"
    
